name: Update XML

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_xml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas lxml openpyxl

    - name: Display files before script
      run: |
        echo "Файлы перед выполнением скрипта:"
        ls -1

    - name: Run update script
      run: |
        echo "Запуск скрипта обновления XML..."
        python update_xml.py
        echo "Содержимое после выполнения скрипта:"
        ls -1
      env:
        stock_file: "$(ls | grep '2024' | grep '.xlsx' || true)"
        price_file: "$(ls | grep 'цены' | grep '.xlsm' || true)"
        xml_file: "intertop.xml"

    - name: Check for changes
      id: git_diff
      run: |
        git diff --exit-code intertop.xml || echo "Изменения найдены"

    - name: Commit changes
      if: steps.git_diff.outputs.exit-code != '0'
      run: |
        git config --global user.name "your-username"
        git config --global user.email "your-email@example.com"
        git add intertop.xml
        git commit -m "Automatically update XML file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up files
      run: |
        echo "Удаление временных файлов..."
        rm -f *.xlsx || echo "Файлы запасов не найдены для удаления"
        rm -f *.xlsm || echo "Файл цен не найден для удаления"
        echo "Файлы после удаления:"
        ls -1
