name: Update XML

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_xml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas lxml openpyxl

    - name: Show working directory content
      run: |
        echo "Содержимое рабочей директории:"
        ls -R

    - name: Find stock files
      id: find_files
      run: |
        STOCK_FILES=$(find . -type f -iregex '.*stock.*\\.\\(xlsx\\|XLSX\\)$' | head -n 2 | tr '\\n' ' ')
        if [ -z "$STOCK_FILES" ]; then
          echo "Error: No stock files found."
          exit 1
        fi
        echo "STOCK_FILES=$STOCK_FILES" >> $GITHUB_ENV

    - name: Find price file
      id: find_price
      run: |
        PRICE_FILE=$(find . -type f -iregex '.*цены.*\\.\\(xlsm\\|XLSM\\)$' || true)
        if [ -z "$PRICE_FILE" ]; then
          echo "Warning: Price file not found. Continuing without it."
        fi
        echo "PRICE_FILE=$PRICE_FILE" >> $GITHUB_ENV

    - name: Run update script
      run: |
        echo "Найденные файлы запасов: $STOCK_FILES"
        echo "Файл цен: $PRICE_FILE"
        python update_xml.py
      env:
        STOCK_FILES: ${{ env.STOCK_FILES }}
        PRICE_FILE: ${{ env.PRICE_FILE }}
        XML_FILE: "intertop.xml"

    - name: Commit changes
      run: |
        if [ -n "$(git status --porcelain | grep 'intertop.xml')" ]; then
          git config --global user.name "nurbekashirbek"
          git config --global user.email "nurbek.a2003@gmail.com"
          git add intertop.xml
          git commit -m "Automatically update XML file"
          git push
        else
          echo "No changes detected in intertop.xml. Skipping commit."
